# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44ca1688e1e1aba771b555c195e72edf16ee2edcfb46a3dc346afe250c3abc78bcb7bbd8e421a5d2e7db17d1ae706654d8b76aa41467f86677d0e6c5b8e8767c

test:
  secret_key_base: eb354b7735b3762661a1a0a4c68bc6b52cb5ba7cc7b6ec403226e838f91964c57fed1bae806d48b51193cf9e51723f83352809f2b638ed909ab2e028a2abc8e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
